services:
  influxdb:
    image: influxdb:3.9.3-core
    container_name: tsdb-influxdb3
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --admin-token-file=/run/secrets/influxdb3-admin-token
    volumes:
      - ./data/influxdb3/data:/var/lib/influxdb3/data
      - ./data/influxdb3/plugins:/var/lib/influxdb3/plugins
    secrets:
      - influxdb3-admin-token
    restart: unless-stopped

  iotdb:
    image: apache/iotdb:2.0.8-standalone
    container_name: tsdb-iotdb
    hostname: iotdb
    ports:
      - "6667:6667"
    privileged: true
    volumes:
      - ./data/iotdb2:/iotdb/data
      - ./data/iotdb2-logs:/iotdb/logs
    environment:
      - cn_internal_address=iotdb
      - cn_internal_port=10710
      - cn_consensus_port=10720
      - cn_seed_config_node=iotdb:10710
      - dn_rpc_address=iotdb
      - dn_internal_address=iotdb
      - dn_rpc_port=6667
      - dn_internal_port=10730
      - dn_mpp_data_exchange_port=10740
      - dn_schema_region_consensus_port=10750
      - dn_data_region_consensus_port=10760
      - dn_seed_config_node=iotdb:10710
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    restart: unless-stopped

  postgres:
    image: postgres:18.4
    container_name: tsdb-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_USER: postgres
      POSTGRES_DB: droid
    shm_size: 256mb
    restart: unless-stopped

  mysql:
    image: docker.m.daocloud.io/library/mysql:8.4
    container_name: tsdb-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql8:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: droid
    restart: unless-stopped

  dolphindb:
    image: dolphindb/dolphindb:v3.00.5
    container_name: tsdb-dolphindb
    hostname: dolphindb
    ports:
      - "8848:8848"
    restart: unless-stopped

secrets:
  influxdb3-admin-token:
    file: ./config/influxdb3-admin-token.json
